### ISSUE TITLE
Regarding nb_epochs and nb_digits

### ISSUE THREAD

**Issue by saikumarkethi** [VieVie31/cool-papers-in-pytorch#6]
there is some error in the code there is no reason to use nb_epochs and nb_digits no where you have used

**Comment by VieVie31** [comment]
Hi !

Just to be clear, this repository contains some draft code I wrote just after reading the corresponding papers.
So, there is no intention to repoduce the state of the art results or make it ready for industrial use, juste to see how the "stuff works"...
I already linked you the implementation written by the author in your previous pull request and since you seem hightly interested by this paper you should prefer using the official implementation instead.

Best Regards,
Olivier

PS : Please, stop spamming 

![STOP SPAM](https://i.ibb.co/28FBcyv/Capture.png)
